### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by blooketshark** [DaveH355/arcademics-helper#1]
hi the thing is not working and when I make it an extension it comes up with like 8 errors

![image](https://user-images.githubusercontent.com/96549895/214670176-290db1f3-53af-49ab-925c-23a0ad89f67b.png)
![image](https://user-images.githubusercontent.com/96549895/214670189-b9280fc8-cb07-4633-b844-f77e90310859.png)
![image](https://user-images.githubusercontent.com/96549895/214670196-f6a996e0-30eb-4435-9710-d45aa9a28774.png)

**Comment by DaveH355** [comment]
The errors shouldn't affect the bot from working. Have you tested it yet?

**Comment by blooketshark** [comment]
yes

**Comment by blooketshark** [comment]
could you pls make a vid of how to do it set it up

**Comment by DaveH355** [comment]
@blooketshark A video isn't necessary. The setup is pretty straightforward already. 

Try downloading the bot again as there are some slight changes.  The readme also now has a troubleshooting section. Let me know if it works for you. 

Just tested the bot right now and it's working.

**Comment by blooketshark** [comment]
sorry i just noticed i had to press A to do it ty for your help. could you also maybe make an anti ban?

**Comment by DaveH355** [comment]
I'm assuming "anti ban" refers to scores getting removed from the leaderboard. It's not possible to stop that.

**Comment by blooketshark** [comment]
ok is there a way to hide the "academics helper"
