### ISSUE TITLE
its not working now

### ISSUE THREAD

**Issue by blooketshark** [DaveH355/arcademics-helper#3]
I've re-installed it but when i press A it dose nothing.

**Comment by DaveH355** [comment]
First, before joining a game, click on the extension to activate it
It's also possible you opened another tab after turning on the extension. In which case, just close the "Arcademics Helper" debug message and reactivate the extension

I have just tested it, and it's still working

**Comment by blooketshark** [comment]
it s still not working

**Comment by blooketshark** [comment]
iv do evry thing uv told me to do but it still wont work can u pls make a small vid or screen shots of how to do it

**Comment by DaveH355** [comment]
What website are you on? It doesn't work for plus.arcademics.com
Only arcademics.com

**Comment by blooketshark** [comment]
no

**Comment by blooketshark** [comment]
> What website are you on? It doesn't work for plus.arcademics.com Only arcademics.com

 Why dose it not work plus the first time it worked and how to I switch to academics.com it always switch is to plus.

**Comment by blooketshark** [comment]
have you deleted it and re installed it

**Comment by blooketshark** [comment]
@DaveH355 

> > What website are you on? It doesn't work for plus.arcademics.com Only arcademics.com
> 
> Why dose it not work plus the first time it worked and how to I switch to academics.com it always switch is to plus.

@DaveH355

**Comment by DaveH355** [comment]
Sounds like you just need to log out of your arcademics plus account. Then arcademics.com should load fine.

**Comment by blooketshark** [comment]
is there a way that you can code It into the script

**Comment by blooketshark** [comment]
i think it worked on plus the first time tho because I was logged in

**Comment by DaveH355** [comment]
plus.arcademics.com is now supported
