### ISSUE TITLE
if logged in account bot no work

### ISSUE THREAD

**Issue by hmmmmmmLigma** [DaveH355/arcademics-helper#7]
ok so u read the title when i log in to an account the bot just doesnt work. ive tried to re download multiple times and it only works when im not logged in.

**Comment by DaveH355** [comment]
The bot won't work on assignments where the url looks something like `https://plus.arcademics.com/assignments/9836577`. It should work otherwise when logged in.

**Comment by hmmmmmmLigma** [comment]
i see. in the past it did work on assignments but i guess code doesnt work on it or arca patched it.

**Comment by DaveH355** [comment]
Ah yes, the code has changed to support more game modes. It looks at the url to figure out the game mode and the assignments url is throwing it off. I'll see later if there's a fix

**Comment by hmmmmmmLigma** [comment]
oh okay late response but can you send me the old arcademics bot?  cause that one could run assignments

**Comment by DaveH355** [comment]
Fixed in dba6ad5. It should work on assignments now. Let me know if there are any more problems.
